name: Version Sync Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    name: Ensure Node and Python versions match
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check version consistency
        run: npm run check:version
